apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
#encode your pass like this and paste below: ubuntu@ip-172-31-90-20:~$ echo -n "vprodbpass" | base64
#dnByb2RicGFzcw==
  db-pass: dnByb2RicGFzcw==
  rmq-pass: Z3Vlc3Q=